# Default values for route53-healthcheck-status.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: readytalk/route53-healthcheck-status
  tag: 0.0.1
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: 100m
   memory: 64Mi
  requests:
   cpu: 100m
   memory: 64Mi

config: ""
