apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "route53-healthcheck-status.fullname" . }}
  labels:
    app: {{ template "route53-healthcheck-status.name" . }}
    chart: {{ template "route53-healthcheck-status.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "route53-healthcheck-status.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "route53-healthcheck-status.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID_FETCH
              value: {{ .Values.AWS_ACCESS_KEY_ID_FETCH | quote }}
            - name: AWS_SECRET_ACCESS_KEY_FETCH
              value: {{ .Values.AWS_SECRET_ACCESS_KEY_FETCH | quote }}
            - name: AWS_ACCESS_KEY_ID_POST
              value: {{ .Values.AWS_ACCESS_KEY_ID_POST | quote }}
            - name: AWS_SECRET_ACCESS_KEY_POST
              value: {{ .Values.AWS_SECRET_ACCESS_KEY_POST | quote }}
          volumeMounts:
          - name: config-volume
            mountPath: /config.json
            subPath: config.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "route53-healthcheck-status.fullname" . }}
